services:
  headlessx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: headlessx
    ports:
      - "3000"    # Only expose container port, let Coolify handle routing
    environment:
      - DOMAIN=${DOMAIN:-localhost}            # Your domain
      - SUBDOMAIN=${SUBDOMAIN:-headlessx}      # Your subdomain
      - PORT=3000
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=128
      - NODE_OPTIONS=--max-old-space-size=4096
    env_file:
      - .env                            # Load from .env file in root directory
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs                  # Persistent logs
      - /tmp:/tmp                          # Temporary files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 512M
          cpus: '0.5'
    networks:
      - headlessx-network
    security_opt:
      - no-new-privileges:true

networks:
  headlessx-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: headlessx0
