version: '3.8'

services:
  headlessx:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: headlessx
    ports:
      - "80:80"        # Nginx serving website and proxying API
      - "3000:3000"    # Direct API access (optional for debugging)
    environment:
      - TOKEN=${TOKEN}  # REQUIRED: Set this in your environment
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - /tmp:/tmp  # For temporary files
      - ../logs:/app/logs  # Persistent logs
      - ../website/out:/var/www/headlessx  # Website static files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    networks:
      - headlessx-network

networks:
  headlessx-network:
    driver: bridge
